version: '3'
services:
  postgresql:
    container_name: postgresql
    build: ./postgresql
    ports:
      - "5111:5432"
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    restart: always
  new-db:
    container_name: new-db
    build: ./postgresql
    ports:
      - "5112:5432"
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    restart: always