version: '3'
services:
  postgresql:
    container_name: postgresql
    build: ./postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    restart: always






  # app:
  #   image: node:18-alpine
  #   volumes:
  #     - ./app/:/app/
  #   ports:
  #     - "3000:3000"
  #   tty: true
  #   working_dir: /app/client
  #   command: npm run dev