service: apollo-lambda
provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1
functions:
  graphql:
    handler: index.graphqlHandler
    events:
      - http:
          path: /
          method: post
          cors: true
